# Site Settings
locale                   : "en-US"
title                    : "Junteng Liu"
title_separator          : "-"
subtitle                 : 
name                     : &name "Junteng Liu"
description              : &description "Personal homepage of Junteng Liu"
url                      : https://rusgye02-automation.github.io
baseurl                  : /LJT-Homepage
repository               : "rusgye02-automation/LJT-Homepage"
teaser                   : 
breadcrumbs              : false
words_per_minute         : 200
comments:
  provider               : false
atom_feed:
  path                   : 
search                   : true
search_full_content      : true
search_provider          : lunr

# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "junteng88716710"
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : 

# Site Author
author:
  name             : "Junteng Liu"
  avatar           : 
  bio              : "First-year PhD candidate at HKUST NLP Group."
  location         : "Hong Kong"
  email            : jliugi@connect.ust.hk
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : Vicent0205
  google_plus      :
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         :
  orcid            :
  pinterest        :
  soundcloud       :
  stackoverflow    :
  steam            :
  tumblr           :
  twitter          : junteng88716710
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
  googlescholar    : "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  semanticscholar  :
  researchgate     :
  publons          :

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jliugi@connect.ust.hk"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Hong_Kong

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

publication_category:
  conferences:
    title: Conference Papers
  preprints:
    title: Preprints
